version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mafia-mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mafia-mongo-volume:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

volumes:
  mafia-mongo-volume:
